title = "Signal"

[docusaurus]

[[classOrder]]
section = "Utilities"
collapsed = false
classes = ["Signal", "Connection", "ThreadPool"]

[[navbar.items]]
href = "https://discord.gg/gMWmuaZEY6"
label = "Discord"
position = "right"

[footer]
style = "dark"
copyright = "Copyright © 2023 YetAnotherClown. Built with Moonwave and Docusaurus"

[[footer.links]]
title = "Links"

[[footer.links.items]]
label = "Clown's Circus Discord"
href = "https://discord.gg/gMWmuaZEY6"

[[footer.links.items]]
label = "YetAnotherClown on Github"
href = "https://github.com/YetAnotherClown"